[package]
name = "hissy"
version = "0.1.0"
authors = ["Luapix <luapixel@gmail.com>"]
edition = "2018"

[lib]
name = "hissy_lib"

[[bin]]
name = "hissy"

[dependencies]
peg = "0.6.1"
unicode-xid = "0.2.0"
smallstr = "0.2.0"
num_enum = "0.4.2"
dtoa = "0.4.5"
docopt = "1.1.0"
